# Generated by Django 5.0.2 on 2024-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Earphones'), (2, 'Speaker'), (3, 'Mobile'), (4, 'Camera')], verbose_name='Category'),
        ),
    ]
